### ISSUE TITLE
Link to section

### ISSUE THREAD

**Issue by garcianna** [ubidi/REDCapDM#2]
# Link to section

I find it interesting to be able to include in the query file the link to the field to be modified. In this way the center will be able to access more efficiently.

Any section of a REDCap project have REDCap version, project id, event id and record id
https://redcap.fls-rs.com/redcap_v**13.3.0**/DataEntry/record_home.php?pid=**929**&arm=1&id=**1**

#PYTHON sintax
#To add the links to the IDs  cell.value=1

for sheet in wb:
    if sheet['B2'].value == 'record_id':
        sheet['B1'].value = sheet['A1'].value
        sheet.delete_cols(idx=1, amount=1)
    colC = sheet['A']
    for row in sheet:
        for cell in colC:
            cell.hyperlink = "https://redcap.fls-rs.com/redcap_v13.3.0/DataEntry/record_home.php?pid=929&arm=1&id=" + str(cell.value)
            cell.style = "Hyperlink"

**Comment by jcarmezim** [comment]
Dear Anna,
First of all, thank you very much for your input.
Your idea seems very interesting. We will explore how to incorporate this to the function as we have to take in account that every institution and every project has its own link. Our first thought is to create a new argument that will let you input this specific link.
