### ISSUE TITLE
Advertise on REDCap Tools

### ISSUE THREAD

**Issue by wibeasley** [ubidi/REDCapDM#3]
I just noticed this packages (with its dependency on REDCapR).  Good job putting it together and getting it on CRAN.

Consider listing your package on this page so more people might stumble in it (especially for those developers not on the community site).

https://redcap-tools.github.io/projects/

**Comment by jcarmezim** [comment]
Hi Will

Thank you for your feedback and support.
We would be grateful to have our package listed in your website.

Best regards,
REDCapDM
